# Konfiguracja TimeReward
reward-interval: 5   # Czas (w minutach) między nagrodami
max-time: 300         # Maksymalny czas (w minutach), po którym gracz przestaje dostawać nagrody (5 godzin = 300 minut)
reward-amount: 15     # Kwota nagrody za każde 10 minut gry
